const Privacy = () => {
    return (
        <section class="py-8 lg:py-16 px-4 mx-auto max-w-screen-md">
            <h1>Privacy Policy</h1>
                <p>Last updated: January 15, 2025</p>
                <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Website and tells You about Your privacy rights and how the law protects You.</p>
                <p className="mb-3">We use Your Personal data to provide and improve the Website. By using the Website, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the <a href="https://www.termsfeed.com/privacy-policy-generator/" aria-label="Link to terms feed" target="_blank">Privacy Policy Generator</a>.</p>
            <h2 className="mb-3">Interpretation and Definitions</h2>
                <h3>Interpretation</h3>
                    <p className="mb-3">The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
                <h3>Definitions</h3>
                    <p>For the purposes of this Privacy Policy:</p>
                    <ul className="mb-3 list-disc xs:w-[75vw] lg:w-[30vw] justify-center mx-auto"> 
                        <li>
                            <p><strong>Memorial Fund</strong> (referred to as either &quot;the Memorial Fund&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to Scott Adams Sr. Memorial Fund, Bethlehem, PA 18017.</p>
                        </li>
                        <li>
                            <p><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</p>
                        </li>
                        <li>
                            <p><strong>Country</strong> refers to: United States</p>
                        </li>
                        <li>
                            <p><strong>Device</strong> means any device that can access the Website such as a computer, a cellphone or a digital tablet.</p>
                        </li>
                        <li>
                            <p><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</p>
                        </li>
                        <li>
                            <p><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Website or from the Website infrastructure itself (for example, the duration of a page visit).</p>
                        </li>
                        <li>
                            <p><strong>Website</strong> refers to Scott Adams Sr. Memorial Fund, accessible from <a className="underline hover:text-secondary" href="https://scottadamssrmemorialfund.org" aria-label="link to home page" rel="external nofollow noopener" target="_blank">https://scottadamssrmemorialfund.org</a></p>
                        </li>
                        <li>
                            <p><strong>You</strong> means the individual accessing or using the Website, or the Memorial Fund, or other legal entity on behalf of which such individual is accessing or using the Website, as applicable.</p>
                        </li>
                    </ul>
            <h2 className="mb-3">Collecting and Using Your Personal Data</h2>
                <h3 className="mb-3">Types of Data Collected</h3>
                    <h4>Personal Data</h4>
                        <p className="mb-3">While using Our Website, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
                            <ul className="mb-3 list-disc xs:w-[75vw] lg:w-[30vw] justify-center mx-auto">
                                <li>
                                    <p>Email address</p>
                                </li>
                            </ul>
                        <p>Your email address is only collected if you supply it via the Contact form located at <a className="underline hover:text-secondary" aria-label="Link to contact page" href="/contact">https://scottadamssrmemorialfund.org/contact</a> or if you subscribe to our Newsletter.</p> 
                        <p className="mb-3">We will collect any other data you supply within the message box via the Contact form. </p>
                    <h4>Usage Data</h4>
                        <p className="mb-3">No Usage Data is collected while using the Website.</p>
                    <h4>Tracking Technologies and Cookies</h4>
                        <p className="mb-3">We do not use cookies or any tracking technologies to collect Your Personal Data.</p>
                <h3>Use of Your Personal Data</h3>
                    <p>The Memorial Fund may use Personal Data for the following purposes:</p>
                    <ul className="mb-3 list-disc xs:w-[75vw] lg:w-[30vw] justify-center mx-auto">
                        <li>
                            <p><strong>To provide and maintain our Website</strong>, including to monitor the usage of our Website.</p>
                        </li>
                        <li>
                            <p><strong>To contact You:</strong> To contact You by email if You request to be contacted.</p>
                        </li>
                        <li>
                            <p><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</p>
                        </li>
                        <li>
                            <p><strong>With Your consent:</strong> We may disclose Your personal information for any other purpose with Your consent.</p>
                        </li>
                    </ul>
                    <p className="mb-3">If you subscribe to our Newsletter, Your email address with be shared with <a className="hover:text-secondary" aria-label="Link to beehiiv" href="https://www.beehiiv.com/"><u>Beehiv.</u> </a> 
                    For information on how they protect Your Personal Data, please checkout their <a className="underline hover:text-secondary" aria-label="Link to Privacy Policy of beehiiv" href="https://www.iubenda.com/privacy-policy/39979771/full-legal">Privacy Policy.</a></p>
                    <p className="mb-3">If you reach out to us via our contact form, Your email is shared with <a className="hover:text-secondary" aria-label="Link to Web 3 Forms" href="https://web3forms.com/"><u>Web3Forms</u>. </a> Web3Forms does not save your data. For more
                    information on how they handle Your Personal Data, please checkout their <a className="underline hover:text-secondary" aria-label="Link to Web 3 Forms Privacy Policy" href="https://web3forms.com/privacy">Privacy Policy.</a></p>

                <h3>Retention of Your Personal Data</h3>
                   <p className="mb-3">The Memorial Fund will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
                <h3>Transfer of Your Personal Data</h3>
                   <p>Your information, including Personal Data, is processed at the Memorial Fund's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.</p>
                   <p>Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</p>
                   <p className="mb-3">The Memorial Fund will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.</p>
                <h3>Delete Your Personal Data</h3>
                   <p>You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.</p>
                   <p>You may contact Us to request access to, correct, or delete any personal information that You have provided to Us.</p>
                   <p className="mb-3">Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.</p>
                <h3>Disclosure of Your Personal Data</h3>
                   <h4>Law enforcement</h4>
                        <p className="mb-3">Under certain circumstances, the Memorial Fund may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>
                   <h4>Other legal requirements</h4>
                        <p className="mb-3">The Memorial Fund may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
                        <ul className="mb-3 list-disc xs:w-[75vw] lg:w-[30vw] justify-center mx-auto">
                            <li><p>Comply with a legal obligation</p></li>
                            <li><p>Protect and defend the rights or property of the Memorial Fund</p></li>
                            <li><p>Prevent or investigate possible wrongdoing in connection with the Website</p></li>
                            <li><p>Protect the personal safety of Users of the Website or the public</p></li>
                            <li><p>Protect against legal liability</p></li>
                        </ul>
                <h3>Security of Your Personal Data</h3>
                    <p className="mb-3">The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>
            <h2>Children's Privacy</h2>
                <p>Our Website does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.</p>
                <p className="mb-3">If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.</p>
            <h2>Links to Other Websites</h2>
                <p>Our Website may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.</p>
                <p className="mb-3">We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or Websites.</p>
            <h2>Changes to this Privacy Policy</h2>
                <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
                <p>We will let You know via a prominent notice on Our Website, prior to the change becoming effective and update the &quot;Last updated&quot; date at the top of this Privacy Policy.</p>
                <p className="mb-3">You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
            <h2>Contact Us</h2>
                <p>If you have any questions about this Privacy Policy, You can contact us:</p>
                <ul className="list-disc xs:w-[75vw] lg:w-[30vw] justify-center mx-auto mb-20">
                    <li>
                        <p>By email: scottadamssrmemorialfund@gmail.com</p>
                    </li>
                    <li>
                        <p>By visiting this page on our website: <a href="https://scottadamssrmemorialfund.org/contact" aria-label="Link to contact page" rel="external nofollow noopener" target="_blank" className="hover:text-secondary underline">https://scottadamssrmemorialfund.org/contact</a></p>
                    </li>
                </ul>
            </section>
    )
}

export default Privacy;