export const navData = [
    ['home', 'Home', '/', "Link to Home Page"],
    ['upcoming', 'Upcoming Events', '/upcoming', "Link to Upcoming Events Page"],
    ['past', 'Past Events', '/past', "Link to Past Events Page"],
    ['sponsors', 'Sponsors', '/sponsors', "Link to Sponsors Page"]
]

export const donationData = [
    [2010, "Bowling", 20, "$300", "$500", "$0", "$800"],
    [2011, "Bowling", 36, "$540", "$503", "$100", "$1,143"],
    [2012, "Bowling", 40, "$720", "$765", "$315", "$1,800"],
    [2013, "Bowling", 71, "$1,420", "$820", "$160", "$2,400"],
    [2014, "Bowling", 70, "$1,400", "$905", "$335", "$2,640"],
    [2015, "Bowling", 64, "$1,280", "$587", "$411", "$2,278"],
    [2016, "Bowling", 68, "$1,370", "$1,025", "$1,157", "$3,552"],
    [2017, "Bowling", 77, "$1,540", "$1,390", "$8,388", "$11,318"],
    [2018, "Bowling", 73, "$1,460", "$1,421", "$6,300", "$9,181"],
    [2019, "Bowling", 82, "$1,640", "$1,897", "$4,873", "$8,410"],
    [2020, "Bowling", 80, "$1,630", "$2,142", "$6,850", "$10,622"],
    [2021, "Cornhole", 64, "$1,280", "$2,220", "$4,000", "$7,500"],
    [2022, "Cornhole", 94, "$1,880", "$3,120", "$6,800", "$11,800"],
    [2023, "Cornhole", 96, "$1,920", "$4,110", "$7,300", "$13,330"],
    [2024, "Cornhole", 102, "$2,040", "$3,665", "$9,330", "$15,035"],
    [2025, "Cornhole", 112, "$2,240", "$5,350", "$14,431", "$22,021"],
    ["Other", "Bowling/Golf", "", "", "", "", "$58,062"]

]

export const sponsorsMap = [
    ["Critical Acclaim Tattoos", "https://www.facebook.com/CriticalAcclaimTattoos/", "Link to Critical Acclaim Tattoos"],
    ["Adams' Salads", "https://www.facebook.com/adamssalads/", "Link to Adams' Salads"],
    ["Albright's Hardware", "https://www.albrightshardware.com/", "Link to Albright's Hardware"],
    ["Allentown Appliance", "https://www.allentownappliance.com/", "Link to Allentown Appliance"],
    ["Allentown Farmers Market", "https://www.allentownfarmersmarket.com/", "Link to Allentown Farmers Market"],
    ["American Legion Post 576", "https://www.facebook.com/vetswestend/", "Link to American Legion Post 576"],
    ["B.A.C.K. Bikers Against Cop Killers", "https://backmc.org/", "Link to Bikers Against Cop Killers"],
    ["Babe & Jeff", "#", "No link"],
    ["Banko Beverage", "https://bankobeverage.com/", "Link to Banko Beverage"],
    ["Bill & Diane Downing", "#", "No link"],
    ["Bob Eichelburger", "#", "No link"],
    ["Bob Vally Wide Carpet Care", "https://bobsvalleywide.com/", "Link to Bob Vally Wide Carpet Care"],
    ["The Catty Corner", "https://cattycornerpub.com/", "Link to The Catty Corner"],
    ["Cetronia Fire Co. Social Hall", "https://www.facebook.com/p/Cetronia-Fire-Company-Social-Club-100064243116123/", 
        "Link to Centronia Fire Company Social Hall"],
    ["The Commix Hotel", "https://www.instagram.com/thecommix/", "Link to The Commix Hotel"],
    ["Courtney Remaly", "#", "No link"],
    ["Cracker Barrel", "https://www.crackerbarrel.com/", "Link to Cracker Barrel"],
    ["Cuzin's Pub & Grill", "https://www.facebook.com/CuzinsPubandGrill/", "Link to Cuzin's Pub"],
    ["DanJon Management", "https://danjonmgmt.com/", "Link to DanJon Management"],
    ["Dave's Vacuum Cleaner Service", "https://davesvac.com/", "Link to Dave's Vacuum Cleaner Service"],
    ["Deja Brew", "https://www.facebook.com/dejabrewbethlehem/", "Link to Deja Brew"],
    ["Don & Linda Keller", "#", "No link"],
    ["Doug & Nancy Jones", "#", "No link"],
    ["Fairview Fire Co.", "https://www.facebook.com/fairviewfirecompany11/", "Link to Fairview Fire Company"],
    ["Foundation Tavern", "https://www.facebook.com/Foundationtavern/", "Link to Foundation Tavern"],
    ["Franklin Social Club", "https://m.facebook.com/profile.php?id=215772792360139", "Link to Franklin Social Club"],
    ["Giant Food Stores", "https://giantfoodstores.com/", "Link to Giant Food Store"],
    ["Giovanni's Pizza", "https://www.giovannispizzaallentown.com/", "Link to Giovanni's Pizza"],
    ["Heckenberger's Seafood", "https://www.facebook.com/heckenbergers/", "Link to Heckenberger's Seafood"],
    ["Henry's Salt of the Sea", "https://henryssaltofthesea.com/", "Link to Henry's Salt of the Sea"],
    ["Hogan's Social Club", "https://www.facebook.com/p/Hogans-of-Allentown-PA-100063715533723/", "Link to Hogan's Social Club"],
    ["Hops at the Paddock", "https://www.hopslehighvalley.com/paddock/menus/", "Link to Hops at the Paddock"],
    ["Jack's Slice", "https://jacksslice.com/", "Link to Jack's Slice"],
    ["Jan & Deb Schuster", "#", "No link"],
    ["Jeff Schlier", "#", "No link"],
    ["Jenny's Gift Baskets", "https://jennysgiftbaskets.com/", " Link to Jenny's Gift Baskets"],
    ["Jersey Mike's Subs", "https://www.jerseymikes.com/", "Link to Jersey Mike's Subs"],
    ["Jessica Lohse", "#", "No link"],
    ["Jim Fink", "#", "No link"],
    ["Jimmy's Barber Shop", "https://jimmysbarbershopallentown.com/", "Link to Jimmy's Barber Shop"],
    ["JoAnne Adams", "#", "No link"],
    ["Joe Holloman", "#", "No link"],
    ["Joe Tatasciore", "#", "No link"],
    ["Kathy Bernhard", "#", "No link"],
    ["Keystone Pub & Grille", "https://keystonepub.com/", "Link to Keystone Pub & Grille"],
    ["Kid's Kingdom Day Care Center", "https://www.facebook.com/kidskingdomdaycarecenter", "Link to Kid's Kingdom Day Care Center"],
    ["King Kone", "http://kingkonewhitehall.com/", "Link to King Kone"],
    ["Kuhnsville Hotel", "https://www.facebook.com/p/Kuhnsville-Hotel-100063693632560/", "Link to Kuhnsville Hotel"],
    ["Liberty Bell Beverage", "https://www.instagram.com/libertybellbeverage/", "Link to Liberty Bell Beverage"],
    ["LLS Graphics", "https://www.llsgraphics.com/", "Link to LLS Graphics"],
    ["Lowe's", "https://www.lowes.com/", "Link to Lowe's"],
    ["The Lucky Bamboo Store", "https://theluckybamboostore.com/", "Link to The Lucky Bamboo Store"],
    ["Lucy & Lolly's All Natural Pit Stop", "https://www.facebook.com/LucyandLollys/", "Link to Lucy & Lolly's All Natural Pit Stop"],
    ["Mahoney's Irish Pub", "https://www.mahoneysirishpubpa.com/", "Link to Mahoney's Irish Pub"],
    ["Mickley Run Apartments", "https://danjonmgmt.com/property/mickley-run/", "Link to Mickley Run Apartments"],
    ["Mike & Donna Kincaid", "#", "No link"],
    ["Mike Daddona", "#", "No link"],
    ["Mildred Hamersly", "#", "No link"],
    ["Mink's Candies", "https://www.facebook.com/p/Minks-Candies-100046229326181/", "Link to Mink's Candies"],
    ["Morgan's Restaurant", "https://www.morgansrest.net/", "Link to Morgan's Restaurant"],
    ["Mountainville Fire Co.", "https://www.facebook.com/p/Mountainville-Fire-Co-16-100087790577058/", "Link to Mountainville Fire Co."],
    ["Mr. Bill's Poultry", "https://mrbills.com/", "Link to Mr. Bill's Poultry"],
    ["Northampton Seafood", "https://www.facebook.com/northamptonseafood/", "Link to Northampton Seafood"],
    ["Olive Garden", "https://www.olivegarden.com/home", "Link to Olive Garden"],
    ["Outback Steakhouse", "https://www.outback.com/", "Link to Outback Steakhouse"],
    ["Parkview Apartments", "https://www.danjonapartmentslv.com/parkview_apartments", "Link to Parkview Apartments"],
    ["Pat Loughlin", "#", "No link"],
    ["Pete Bachman", "#", "No link"],
    ["Phoebe Floral Shop", "https://www.phoebefloral.com/", "Link to Phoebe Floral Shop"],
    ["P.J. Whelihan's", "https://pjspub.com/", "Link to P.J. Whelihan's"],
    ["Red Robin", "https://www.redrobin.com/", "Link to Red Robin"],
    ["Redner's Markets", "https://www.rednersmarkets.com/", "Link to Redner's Markets"],
    ["Render Impact", "https://renderimpact.com/", "Link to Render Impact"],
    ["Ringer's Roost", "https://www.ringersroostpa.com/", "Link to Ringer's Roost"],
    ["Rosemont Fire Co", "https://rosemontfirecompany.com/", "Link to Rosemont Fire Co"],
    ["S. Clyde Weavers", "https://sclydeweaver.com/", "Link to S. Clyde Weavers"],
    ["Sal's Pizza", "https://thesalspizza.com/order%20now.htm", "Link to Sal's Pizza"],
    ["Salvatore Ruffino's Pizza", "https://www.salvatoreruffinos.com/", "Link to Salvatore Ruffino's Pizza"],
    ["Sarah Buck", "#", "No link"],
    ["Shepherd Hills Golf Club", "https://www.shepherdhillsgolf.com/", "Link to Shepherd Hills Golf Club"],
    ["Sleek Styles Salon", "https://www.facebook.com/sleekstylessalon/", "Link to Sleek Styles Salon"],
    ["Stoltzfus Amish Meats", "https://www.stoltzfusmeats.com/", "Link to Stoltzfus Amish Meats"],
    ["Studio 924", "https://studio924salon.com/", "Link to Studio 924"],
    ["Superior Restaurant", "https://superiorrestaurantpa.com/", "Link to Superior Restaurant"],
    ["Sweet Spot Bar and Grille", "https://thesweetspotpa.com/", "Link to Sweet Spot Bar and Grille"],
    ["Texas Roadhouse", "https://www.texasroadhouse.com/", "Link to Texas Roadhouse"],
    ["TGI Friday's", "http://www.tgifridays.com/", "Link to TGI Friday's"],
    ["The Shanty on 19th", "https://www.theshantyon19th.com/", "Link to The Shanty on 19th"],
    ["Tim Schaeffer", "#", "No link"],
    ["Todds Island Seafood", "https://www.facebook.com/@ToddsIslandSeafood/", "Link to Todds Island Seafood"],
    ["Turczyn Amusements", "#", "No link"],
    ["Twin Lakes Golf Club", "https://www.theclubattwinlakes.com/", "Link to Twin Lakes Golf Club"],
    ["Udder Bar", "https://www.theudderbar.com/", "Link to Udder Bar"],
    ["Villa Lentini Ristorante", "https://villalentinirestaurant.com/", "Link to Villa Lentini Ristorante"],
    ["Volpe's Sports Bar & Grill", "https://volpessportsbar.com/", "Link to Volpe's Sports Bar & Grill"],
    ["Vynecrest Winery", "https://www.vynecrest.com/", "Link to Vynecrest Winery"],
    ["Wally's Deli", "https://wallys-deli.com/", "Link to Wally's Deli"],
    ["Wanderer Coffee", "https://wanderercoffeeco.com/", "Link to Wanderer Coffee"],
    ["Wawa", "https://www.wawa.com/", "Link to Wawa"],
    ["Wegmans Allentown", "https://www.wegmans.com/", "Link to Wegmans Allentown"],
    ["Weis Markets", "https://www.weismarkets.com/", "Link to Weis Markets"],
    ["Wert's Cafe", "https://wertscafe.com/", "Link to Wert's Cafe"],
    ["Willie Hirshel", "#", "No link"],
    ["Willie Joe's", "https://www.willyjoes.com/", "Link to Willie Joe's"],
    ["Willow Crest Apartments", "https://danjonmgmt.com/property/willow-crest/", "Link to Willow Crest Apartments"],
    ["Willow Street Pub", "https://willowstreetpub.com/", "Link to Willow Street Pub"],
    ["Woodstone Country Club", "https://woodstonegolf.com/aromi", "Link to Woodstone Country Club"],
]
