export const navData = [
    ['home', 'Home', '/'],
    ['upcoming', 'Upcoming Events', '/upcoming'],
    ['news', 'News', 'news'],
    ['past', 'Past Events', 'past'],
    ['sponsors', 'Sponsors', 'sponsors']
]

export const sponsorsMap = [
    ["Critical Acclaim Tattoos", "https://www.facebook.com/CriticalAcclaimTattoos/"],
    ["Adams Salads'", "https://www.facebook.com/adamssalads/"],
    ["Albright's Hardware", "https://www.albrightshardware.com/"],
    ["Allentown Appliance", "https://www.allentownappliance.com/"],
    ["Allentown Farmers Market", "https://www.allentownfarmersmarket.com/"],
    ["American Legion Post 576", "https://www.facebook.com/vetswestend/"],
    ["B.A.C.K. Bikers Against Cop Killers", "https://backmc.org/"],
    ["Babe & Jeff", "#"],
    ["Banko Beverage", "https://bankobeverage.com/"],
    ["Bill & Diane Downing", "#"],
    ["Bob Eichelburger", "#"],
    ["Bob Vally Wide Carpet Care", "https://bobsvalleywide.com/"],
    ["The Catty Corner", "https://cattycornerpub.com/"],
    ["Cetronia Fire Co. Social Hall", "https://www.facebook.com/p/Cetronia-Fire-Company-Social-Club-100064243116123/"],
    ["The Commix Hotel", "https://www.instagram.com/thecommix/"],
    ["Courtney Remaly", "#"],
    ["Cracker Barrel", "https://www.crackerbarrel.com/"],
    ["Cuzin's Pub & Grill", "https://www.facebook.com/CuzinsPubandGrill/"],
    ["DanJon Management", "https://danjonmgmt.com/"],
    ["Dave's Vacuum Cleaner Service", "https://davesvac.com/"],
    ["Deja Brew", "https://www.facebook.com/dejabrewbethlehem/"],
    ["Don & Linda Keller", "#"],
    ["Doug & Nancy Jones", "#"],
    ["Fairview Fire Co.", "https://www.facebook.com/fairviewfirecompany11/"],
    ["Foundation Tavern", "https://www.facebook.com/Foundationtavern/"],
    ["Franklin Social Club", "https://m.facebook.com/profile.php?id=215772792360139"],
    ["Giant Food Stores", "https://giantfoodstores.com/"],
    ["Giovanni's Pizza", "https://www.giovannispizzaallentown.com/"],
    ["Heckenberger's Seafood", "https://www.facebook.com/heckenbergers/"],
    ["Henry's Salt of the Sea", "https://henryssaltofthesea.com/"],
    ["Hogan's Social Club", "https://www.facebook.com/p/Hogans-of-Allentown-PA-100063715533723/"],
    ["Hops at the Paddock", "https://www.hopslehighvalley.com/paddock/menus/"],
    ["Jack's Slice", "https://jacksslice.com/"],
    ["Jan & Deb Schuster", "#"],
    ["Jeff Schlier", "#"],
    ["Jenny's Gift Baskets", "https://jennysgiftbaskets.com/"],
    ["Jersey Mike's Subs", "https://www.jerseymikes.com/"],
    ["Jessica Lohse", "#"],
    ["Jim Fink", "#"],
    ["Jimmy's Barber Shop", "https://jimmysbarbershopallentown.com/"],
    ["JoAnne Adams", "#"],
    ["Joe Holloman", "#"],
    ["Joe Tatasciore", "#"],
    ["Kathy Bernhard", "#"],
    ["Keystone Pub & Grille", "https://keystonepub.com/"],
    ["Kid's Kingdom Day Care Center", "https://www.facebook.com/kidskingdomdaycarecenter"],
    ["King Kone", "http://kingkonewhitehall.com/"],
    ["Kuhnsville Hotel", "https://www.facebook.com/p/Kuhnsville-Hotel-100063693632560/"],
    ["Liberty Bell Beverage", "https://www.instagram.com/libertybellbeverage/"],
    ["LLS Graphics", "https://www.llsgraphics.com/"],
    ["Lowe's", "https://www.lowes.com/"],
    ["The Lucky Bamboo Store", "https://theluckybamboostore.com/"],
    ["Lucy & Lolly's All Natural Pit Stop", "https://www.facebook.com/LucyandLollys/"],
    ["Mahoney's Irish Pub", "https://www.mahoneysirishpubpa.com/"],
    ["Mickley Run Apartments", "https://danjonmgmt.com/property/mickley-run/"],
    ["Mike & Donna Kincaid", "#"],
    ["Mike Daddona", "#"],
    ["Mildred Hamersly", "#"],
    ["Mink's Candies", "https://www.facebook.com/p/Minks-Candies-100046229326181/"],
    ["Morgan's Restaurant", "https://www.morgansrest.net/"],
    ["Mountainville Fire Co.", "https://www.facebook.com/p/Mountainville-Fire-Co-16-100087790577058/"],
    ["Mr. Bill's Poultry", "https://mrbills.com/"],
    ["Northampton Seafood", "https://www.facebook.com/northamptonseafood/"],
    ["Olive Garden", "https://www.olivegarden.com/home"],
    ["Outback Steakhouse", "https://www.outback.com/"],
    ["Parkview Apartments", "https://www.danjonapartmentslv.com/parkview_apartments"],
    ["Pat Loughlin", "#"],
    ["Pete Bachman", "#"],
    ["Phoebe Floral Shop", "https://www.phoebefloral.com/"],
    ["P.J. Whelihan's", "https://pjspub.com/"],
    ["Red Robin", "https://www.redrobin.com/"],
    ["Redner's Markets", "https://www.rednersmarkets.com/"],
    ["Ringer's Roost", "https://www.ringersroostpa.com/"],
    ["Rosemont Fire Co", "https://rosemontfirecompany.com/"],
    ["S. Clyde Weavers", "https://sclydeweaver.com/"],
    ["Sal's Pizza", "https://thesalspizza.com/order%20now.htm"],
    ["Salvatore Ruffino's Pizza", "https://www.salvatoreruffinos.com/"],
    ["Sara Buck", "#"],
    ["Shepherd Hills Golf Club", "https://www.shepherdhillsgolf.com/"],
    ["Sleek Styles Salon", "https://www.facebook.com/sleekstylessalon/"],
    ["Specialized Productions Inc.", "https://www.specializedproductions.com/"],
    ["Stoltzfus Amish Meats", "https://www.stoltzfusmeats.com/"],
    ["Studio 924", "https://studio924salon.com/"],
    ["Superior Restaurant", "https://superiorrestaurantpa.com/"],
    ["Sweet Spot Bar and Grille", "https://thesweetspotpa.com/"],
    ["Texas Roadhouse", "https://www.texasroadhouse.com/"],
    ["TGI Friday's", "http://www.tgifridays.com/"],
    ["The Shanty on 19th", "https://www.theshantyon19th.com/"],
    ["Tim Schaeffer", "#"],
    ["Todds Island Seafood", "https://www.facebook.com/@ToddsIslandSeafood/"],
    ["Turczyn Amusements", "#"],
    ["Twin Lakes Golf Club", "https://www.theclubattwinlakes.com/"],
    ["Udder Bar", "https://www.theudderbar.com/"],
    ["Villa Lentini Ristorante", "https://villalentinirestaurant.com/"],
    ["Volpe's Sports Bar & Grill", "https://volpessportsbar.com/"],
    ["Vynecrest Winery", "https://www.vynecrest.com/"],
    ["Wally's Deli", "https://wallys-deli.com/"],
    ["Wanderer Coffee", "https://wanderercoffeeco.com/"],
    ["Wawa", "https://www.wawa.com/"],
    ["Wegmans Allentown", "https://www.wegmans.com/"],
    ["Weis Markets", "https://www.weismarkets.com/"],
    ["Wert's Cafe", "https://wertscafe.com/"],
    ["Willie Hirshel", "#"],
    ["Willie Joe's", "https://www.willyjoes.com/"],
    ["Willow Crest Apartments", "https://danjonmgmt.com/property/willow-crest/"],
    ["Willow Street Pub", "https://willowstreetpub.com/"],
    ["Woodstone Country Club", "https://woodstonegolf.com/aromi"]
]
